[workspace]
resolver = "2"

members = ["web"]

[workspace.package]
version = "0.1.0"
edition = "2021"

authors = [
    "Matteo Joliveau <oxidrive@matteojoliveau.com>",
]

[workspace.dependencies]
console_error_panic_hook = "0.1.7"
dioxus = "0.5"
dioxus-logger = "0.4.1"
log = "0.4.19"
