/*
 * Oxidrive API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// machine-readable error tag
    #[serde(rename = "error")]
    pub error: String,
    /// human readable error message
    #[serde(rename = "message")]
    pub message: String,
}

impl Error {
    pub fn new(error: String, message: String) -> Error {
        Error { error, message }
    }
}
