/*
 * Oxidrive API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceStatus {
    #[serde(rename = "status")]
    pub status: models::InstanceStatusStatus,
}

impl InstanceStatus {
    pub fn new(status: models::InstanceStatusStatus) -> InstanceStatus {
        InstanceStatus { status }
    }
}
