/*
 * Oxidrive API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Session {
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
}

impl Session {
    pub fn new(token: String, expires_at: String) -> Session {
        Session { token, expires_at }
    }
}
