default:
    @just --list --unsorted | grep -v '  default'

add name:
    for dir in postgres sqlite; do \
      sqlx migrate add -r {{ name }} --source "$dir"; \
    done

run:
    #!/usr/bin/env bash
    set -e

    echo "==== migrating SQLite ===="
    export DATABASE_URL=sqlite://../local/oxidrive.db?mode=rwc
    sqlx migrate run --source sqlite;

    echo "==== migrating PostgreSQL ===="
    export DATABASE_URL=postgres://oxidrive:oxidrive@localhost:5432/oxidrive
    sqlx migrate run --source postgres;

revert:
    #!/usr/bin/env bash
    set -e
    
    echo "==== reverting SQLite ===="
    export DATABASE_URL=sqlite://../local/oxidrive.db?mode=rwc
    sqlx migrate revert --source sqlite;

    echo "==== reverting PostgreSQL ===="
    export DATABASE_URL=postgres://oxidrive:oxidrive@localhost:5432/oxidrive
    sqlx migrate revert --source postgres;

