//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.1-0.20240604070534-2f0ff757704b DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionScopes = "session.Scopes"
)

// Defines values for CredentialsKind.
const (
	CredentialsKindPassword CredentialsKind = "password"
)

// Defines values for FileType.
const (
	FileTypeFile   FileType = "file"
	FileTypeFolder FileType = "folder"
)

// Defines values for InstanceStatusStatusDatabase.
const (
	Postgres InstanceStatusStatusDatabase = "postgres"
	Sqlite   InstanceStatusStatusDatabase = "sqlite"
)

// Defines values for InstanceStatusStatusFileStorage.
const (
	Filesystem InstanceStatusStatusFileStorage = "filesystem"
	S3         InstanceStatusStatusFileStorage = "s3"
)

// Defines values for InvalidFileParamsErrorError.
const (
	InvalidFileParamsErrorErrorInvalidParams InvalidFileParamsErrorError = "invalid_params"
)

// Defines values for InvalidParamsErrorError.
const (
	InvalidParamsErrorErrorInvalidParams InvalidParamsErrorError = "invalid_params"
)

// Defines values for NotFoundErrorError.
const (
	NotFoundErrorErrorNotFound NotFoundErrorError = "not_found"
)

// Defines values for PasswordCredentialsKind.
const (
	PasswordCredentialsKindPassword PasswordCredentialsKind = "password"
)

// Credentials defines model for Credentials.
type Credentials struct {
	Kind  CredentialsKind `json:"kind"`
	union json.RawMessage
}

// CredentialsKind defines model for Credentials.Kind.
type CredentialsKind string

// Error defines model for Error.
type Error struct {
	// Error machine-readable error tag
	Error string `json:"error"`

	// Message human readable error message
	Message string `json:"message"`
}

// File defines model for File.
type File struct {
	ContentType string             `json:"contentType"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Path        string             `json:"path"`

	// Size Size of the file in bytes
	Size int      `json:"size"`
	Type FileType `json:"type"`
}

// FileType defines model for File.Type.
type FileType string

// FileList defines model for FileList.
type FileList struct {
	// Count number of items in the current slice of the collection
	Count int    `json:"count"`
	Items []File `json:"items"`

	// Next Cursor of the next element, to be used as the `after` parameter in paginated operations
	Next *string `json:"next"`

	// Total total number of items in the collection
	Total int `json:"total"`
}

// FilePatch defines model for FilePatch.
type FilePatch struct {
	// Path New path of the file.
	// To simply rename it, set to the current path with the last segment changed.
	// E.g.: path/to/file.txt -> path/to/renamed.txt
	Path *string `json:"path,omitempty"`
}

// FileUpload defines model for FileUpload.
type FileUpload struct {
	File openapi_types.File `json:"file"`
	Path string             `json:"path"`
}

// FileUploadResponse defines model for FileUploadResponse.
type FileUploadResponse struct {
	Id string `json:"id"`
	Ok bool   `json:"ok"`
}

// InstanceSetupRequest defines model for InstanceSetupRequest.
type InstanceSetupRequest struct {
	Admin struct {
		Password string `json:"password"`
		Username string `json:"username"`
	} `json:"admin"`
}

// InstanceSetupResponse defines model for InstanceSetupResponse.
type InstanceSetupResponse struct {
	Ok bool `json:"ok"`
}

// InstanceStatus defines model for InstanceStatus.
type InstanceStatus struct {
	Status struct {
		Database       InstanceStatusStatusDatabase    `json:"database"`
		FileStorage    InstanceStatusStatusFileStorage `json:"fileStorage"`
		PublicURL      string                          `json:"publicURL"`
		SetupCompleted bool                            `json:"setupCompleted"`
	} `json:"status"`
}

// InstanceStatusStatusDatabase defines model for InstanceStatus.Status.Database.
type InstanceStatusStatusDatabase string

// InstanceStatusStatusFileStorage defines model for InstanceStatus.Status.FileStorage.
type InstanceStatusStatusFileStorage string

// InvalidFileParamError defines model for InvalidFileParamError.
type InvalidFileParamError struct {
	Message string `json:"message"`

	// Param The name of the invalid parameter
	Param  string `json:"param"`
	Reason string `json:"reason"`
}

// InvalidFileParamsError defines model for InvalidFileParamsError.
type InvalidFileParamsError struct {
	Error  InvalidFileParamsErrorError `json:"error"`
	Errors []InvalidFileParamError     `json:"errors"`

	// Message human readable error message
	Message string `json:"message"`
}

// InvalidFileParamsErrorError defines model for InvalidFileParamsError.Error.
type InvalidFileParamsErrorError string

// InvalidParamsError defines model for InvalidParamsError.
type InvalidParamsError struct {
	Error InvalidParamsErrorError `json:"error"`

	// Message human readable error message
	Message string `json:"message"`
}

// InvalidParamsErrorError defines model for InvalidParamsError.Error.
type InvalidParamsErrorError string

// ListInfo defines model for ListInfo.
type ListInfo struct {
	// Count number of items in the current slice of the collection
	Count int `json:"count"`

	// Next Cursor of the next element, to be used as the `after` parameter in paginated operations
	Next *string `json:"next"`

	// Total total number of items in the collection
	Total int `json:"total"`
}

// NotFoundError defines model for NotFoundError.
type NotFoundError struct {
	Error NotFoundErrorError `json:"error"`

	// Message human readable error message
	Message string `json:"message"`
}

// NotFoundErrorError defines model for NotFoundError.Error.
type NotFoundErrorError string

// PasswordCredentials defines model for PasswordCredentials.
type PasswordCredentials struct {
	Kind     PasswordCredentialsKind `json:"kind"`
	Password string                  `json:"password"`
	Username string                  `json:"username"`
}

// PasswordCredentialsKind defines model for PasswordCredentials.Kind.
type PasswordCredentialsKind string

// Session defines model for Session.
type Session struct {
	ExpiresAt time.Time `json:"expiresAt"`
	User      User      `json:"user"`
}

// SessionRequest defines model for SessionRequest.
type SessionRequest struct {
	Credentials Credentials `json:"credentials"`
}

// User defines model for User.
type User struct {
	Id       openapi_types.UUID `json:"id"`
	Username string             `json:"username"`
}

// After defines model for After.
type After = string

// FileID defines model for FileID.
type FileID = openapi_types.UUID

// FilePrefix defines model for FilePrefix.
type FilePrefix = string

// First defines model for First.
type First = int

// InternalError defines model for InternalError.
type InternalError = Error

// InvalidParams defines model for InvalidParams.
type InvalidParams = InvalidFileParamsError

// NotFound defines model for NotFound.
type NotFound = NotFoundError

// FilesListParams defines parameters for FilesList.
type FilesListParams struct {
	// First Limit the number of items to return to only the first N
	First *First `form:"first,omitempty" json:"first,omitempty"`

	// After Cursor to fetch the next slice of the collection
	After *After `form:"after,omitempty" json:"after,omitempty"`

	// Prefix Prefix to filter files for. This is matched against the directory the files resides in, not as a generic prefix.
	// E.g. a prefix `hello` will match `hello/world.txt` but not `hello/dear/world.txt`.
	Prefix *FilePrefix `form:"prefix,omitempty" json:"prefix,omitempty"`
}

// FilesUploadMultipartRequestBody defines body for FilesUpload for multipart/form-data ContentType.
type FilesUploadMultipartRequestBody = FileUpload

// FilePatchJSONRequestBody defines body for FilePatch for application/json ContentType.
type FilePatchJSONRequestBody = FilePatch

// InstanceSetupJSONRequestBody defines body for InstanceSetup for application/json ContentType.
type InstanceSetupJSONRequestBody = InstanceSetupRequest

// AuthCreateSessionJSONRequestBody defines body for AuthCreateSession for application/json ContentType.
type AuthCreateSessionJSONRequestBody = SessionRequest

// AsPasswordCredentials returns the union data inside the Credentials as a PasswordCredentials
func (t Credentials) AsPasswordCredentials() (PasswordCredentials, error) {
	var body PasswordCredentials
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPasswordCredentials overwrites any union data inside the Credentials as the provided PasswordCredentials
func (t *Credentials) FromPasswordCredentials(v PasswordCredentials) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePasswordCredentials performs a merge with any union data inside the Credentials, using the provided PasswordCredentials
func (t *Credentials) MergePasswordCredentials(v PasswordCredentials) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Credentials) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["kind"], err = json.Marshal(t.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Credentials) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["kind"]; found {
		err = json.Unmarshal(raw, &t.Kind)
		if err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all available files
	// (GET /api/files)
	FilesList(w http.ResponseWriter, r *http.Request, params FilesListParams)
	// Upload a file to Oxidrive
	// (POST /api/files)
	FilesUpload(w http.ResponseWriter, r *http.Request)
	// Delete a file
	// (DELETE /api/files/{id})
	FileDelete(w http.ResponseWriter, r *http.Request, id FileID)
	// Change a file's metadata
	// (PATCH /api/files/{id})
	FilePatch(w http.ResponseWriter, r *http.Request, id FileID)
	// Get the instance status
	// (GET /api/instance)
	InstanceStatus(w http.ResponseWriter, r *http.Request)
	// Setup the instance and create the initial admin user
	// (POST /api/instance/setup)
	InstanceSetup(w http.ResponseWriter, r *http.Request)
	// Return the user information related to the current session
	// (GET /api/session)
	AuthGetSession(w http.ResponseWriter, r *http.Request)
	// Create a new session and generate the corresponding cookie
	// (POST /api/sessions)
	AuthCreateSession(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// FilesList operation middleware
func (siw *ServerInterfaceWrapper) FilesList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params FilesListParams

	// ------------- Optional query parameter "first" -------------

	err = runtime.BindQueryParameter("form", true, false, "first", r.URL.Query(), &params.First)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "first", Err: err})
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "prefix" -------------

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "prefix", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FilesList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// FilesUpload operation middleware
func (siw *ServerInterfaceWrapper) FilesUpload(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FilesUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// FileDelete operation middleware
func (siw *ServerInterfaceWrapper) FileDelete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id FileID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FileDelete(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// FilePatch operation middleware
func (siw *ServerInterfaceWrapper) FilePatch(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id FileID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FilePatch(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// InstanceStatus operation middleware
func (siw *ServerInterfaceWrapper) InstanceStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InstanceStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// InstanceSetup operation middleware
func (siw *ServerInterfaceWrapper) InstanceSetup(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InstanceSetup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AuthGetSession operation middleware
func (siw *ServerInterfaceWrapper) AuthGetSession(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthGetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AuthCreateSession operation middleware
func (siw *ServerInterfaceWrapper) AuthCreateSession(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthCreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/files", wrapper.FilesList)
	m.HandleFunc("POST "+options.BaseURL+"/api/files", wrapper.FilesUpload)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/files/{id}", wrapper.FileDelete)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/files/{id}", wrapper.FilePatch)
	m.HandleFunc("GET "+options.BaseURL+"/api/instance", wrapper.InstanceStatus)
	m.HandleFunc("POST "+options.BaseURL+"/api/instance/setup", wrapper.InstanceSetup)
	m.HandleFunc("GET "+options.BaseURL+"/api/session", wrapper.AuthGetSession)
	m.HandleFunc("POST "+options.BaseURL+"/api/sessions", wrapper.AuthCreateSession)

	return m
}

type ErrorJSONResponse Error

type InternalErrorJSONResponse Error

type InvalidParamsJSONResponse InvalidFileParamsError

type NotFoundJSONResponse NotFoundError

type FilesListRequestObject struct {
	Params FilesListParams
}

type FilesListResponseObject interface {
	VisitFilesListResponse(w http.ResponseWriter) error
}

type FilesList200JSONResponse FileList

func (response FilesList200JSONResponse) VisitFilesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FilesListdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FilesListdefaultJSONResponse) VisitFilesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FilesUploadRequestObject struct {
	Body *multipart.Reader
}

type FilesUploadResponseObject interface {
	VisitFilesUploadResponse(w http.ResponseWriter) error
}

type FilesUpload200JSONResponse FileUploadResponse

func (response FilesUpload200JSONResponse) VisitFilesUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FilesUpload400JSONResponse struct{ ErrorJSONResponse }

func (response FilesUpload400JSONResponse) VisitFilesUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type FilesUploaddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FilesUploaddefaultJSONResponse) VisitFilesUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FileDeleteRequestObject struct {
	Id FileID `json:"id"`
}

type FileDeleteResponseObject interface {
	VisitFileDeleteResponse(w http.ResponseWriter) error
}

type FileDelete200JSONResponse File

func (response FileDelete200JSONResponse) VisitFileDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FileDelete404JSONResponse struct{ NotFoundJSONResponse }

func (response FileDelete404JSONResponse) VisitFileDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type FileDeletedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FileDeletedefaultJSONResponse) VisitFileDeleteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FilePatchRequestObject struct {
	Id   FileID `json:"id"`
	Body *FilePatchJSONRequestBody
}

type FilePatchResponseObject interface {
	VisitFilePatchResponse(w http.ResponseWriter) error
}

type FilePatch200JSONResponse File

func (response FilePatch200JSONResponse) VisitFilePatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FilePatch400JSONResponse struct{ InvalidParamsJSONResponse }

func (response FilePatch400JSONResponse) VisitFilePatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type FilePatch404JSONResponse struct{ NotFoundJSONResponse }

func (response FilePatch404JSONResponse) VisitFilePatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type FilePatchdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FilePatchdefaultJSONResponse) VisitFilePatchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type InstanceStatusRequestObject struct {
}

type InstanceStatusResponseObject interface {
	VisitInstanceStatusResponse(w http.ResponseWriter) error
}

type InstanceStatus200JSONResponse InstanceStatus

func (response InstanceStatus200JSONResponse) VisitInstanceStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InstanceStatusdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response InstanceStatusdefaultJSONResponse) VisitInstanceStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type InstanceSetupRequestObject struct {
	Body *InstanceSetupJSONRequestBody
}

type InstanceSetupResponseObject interface {
	VisitInstanceSetupResponse(w http.ResponseWriter) error
}

type InstanceSetup200JSONResponse InstanceSetupResponse

func (response InstanceSetup200JSONResponse) VisitInstanceSetupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InstanceSetup400JSONResponse struct{ ErrorJSONResponse }

func (response InstanceSetup400JSONResponse) VisitInstanceSetupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InstanceSetup409JSONResponse Error

func (response InstanceSetup409JSONResponse) VisitInstanceSetupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type InstanceSetupdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response InstanceSetupdefaultJSONResponse) VisitInstanceSetupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type AuthGetSessionRequestObject struct {
}

type AuthGetSessionResponseObject interface {
	VisitAuthGetSessionResponse(w http.ResponseWriter) error
}

type AuthGetSession200JSONResponse Session

func (response AuthGetSession200JSONResponse) VisitAuthGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthCreateSessionRequestObject struct {
	Body *AuthCreateSessionJSONRequestBody
}

type AuthCreateSessionResponseObject interface {
	VisitAuthCreateSessionResponse(w http.ResponseWriter) error
}

type AuthCreateSession200ResponseHeaders struct {
	SetCookie string
}

type AuthCreateSession200JSONResponse struct {
	Body    Session
	Headers AuthCreateSession200ResponseHeaders
}

func (response AuthCreateSession200JSONResponse) VisitAuthCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type AuthCreateSession401JSONResponse struct{ ErrorJSONResponse }

func (response AuthCreateSession401JSONResponse) VisitAuthCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AuthCreateSessiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response AuthCreateSessiondefaultJSONResponse) VisitAuthCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all available files
	// (GET /api/files)
	FilesList(ctx context.Context, request FilesListRequestObject) (FilesListResponseObject, error)
	// Upload a file to Oxidrive
	// (POST /api/files)
	FilesUpload(ctx context.Context, request FilesUploadRequestObject) (FilesUploadResponseObject, error)
	// Delete a file
	// (DELETE /api/files/{id})
	FileDelete(ctx context.Context, request FileDeleteRequestObject) (FileDeleteResponseObject, error)
	// Change a file's metadata
	// (PATCH /api/files/{id})
	FilePatch(ctx context.Context, request FilePatchRequestObject) (FilePatchResponseObject, error)
	// Get the instance status
	// (GET /api/instance)
	InstanceStatus(ctx context.Context, request InstanceStatusRequestObject) (InstanceStatusResponseObject, error)
	// Setup the instance and create the initial admin user
	// (POST /api/instance/setup)
	InstanceSetup(ctx context.Context, request InstanceSetupRequestObject) (InstanceSetupResponseObject, error)
	// Return the user information related to the current session
	// (GET /api/session)
	AuthGetSession(ctx context.Context, request AuthGetSessionRequestObject) (AuthGetSessionResponseObject, error)
	// Create a new session and generate the corresponding cookie
	// (POST /api/sessions)
	AuthCreateSession(ctx context.Context, request AuthCreateSessionRequestObject) (AuthCreateSessionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// FilesList operation middleware
func (sh *strictHandler) FilesList(w http.ResponseWriter, r *http.Request, params FilesListParams) {
	var request FilesListRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FilesList(ctx, request.(FilesListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FilesList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FilesListResponseObject); ok {
		if err := validResponse.VisitFilesListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FilesUpload operation middleware
func (sh *strictHandler) FilesUpload(w http.ResponseWriter, r *http.Request) {
	var request FilesUploadRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FilesUpload(ctx, request.(FilesUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FilesUpload")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FilesUploadResponseObject); ok {
		if err := validResponse.VisitFilesUploadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FileDelete operation middleware
func (sh *strictHandler) FileDelete(w http.ResponseWriter, r *http.Request, id FileID) {
	var request FileDeleteRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FileDelete(ctx, request.(FileDeleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FileDelete")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FileDeleteResponseObject); ok {
		if err := validResponse.VisitFileDeleteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FilePatch operation middleware
func (sh *strictHandler) FilePatch(w http.ResponseWriter, r *http.Request, id FileID) {
	var request FilePatchRequestObject

	request.Id = id

	var body FilePatchJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FilePatch(ctx, request.(FilePatchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FilePatch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FilePatchResponseObject); ok {
		if err := validResponse.VisitFilePatchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InstanceStatus operation middleware
func (sh *strictHandler) InstanceStatus(w http.ResponseWriter, r *http.Request) {
	var request InstanceStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InstanceStatus(ctx, request.(InstanceStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InstanceStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InstanceStatusResponseObject); ok {
		if err := validResponse.VisitInstanceStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InstanceSetup operation middleware
func (sh *strictHandler) InstanceSetup(w http.ResponseWriter, r *http.Request) {
	var request InstanceSetupRequestObject

	var body InstanceSetupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InstanceSetup(ctx, request.(InstanceSetupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InstanceSetup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InstanceSetupResponseObject); ok {
		if err := validResponse.VisitInstanceSetupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthGetSession operation middleware
func (sh *strictHandler) AuthGetSession(w http.ResponseWriter, r *http.Request) {
	var request AuthGetSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthGetSession(ctx, request.(AuthGetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthGetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthGetSessionResponseObject); ok {
		if err := validResponse.VisitAuthGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthCreateSession operation middleware
func (sh *strictHandler) AuthCreateSession(w http.ResponseWriter, r *http.Request) {
	var request AuthCreateSessionRequestObject

	var body AuthCreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthCreateSession(ctx, request.(AuthCreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthCreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthCreateSessionResponseObject); ok {
		if err := validResponse.VisitAuthCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xaWXPbOBL+KyjsVu0LddjxzlQ0NQ9ZZybr2lTiiuOnxDWGyJaECQgwQDOWxqX/voWD",
	"lwhKyvrYvIkg0N34+m7qnqYqL5QEiYbO7mnBNMsBQbunVwsEbX9kYFLNC+RK0hk9L7VRmqAiC8B0RXAF",
	"RMIaiRE8BaIWbiVVQkDqjiSU23NfS9AbmlDJcqAzyhz1hJp0BTmzbHBT2BcGNZdLut0m9Hcu4OJ1X4SL",
	"1xUbDV9LMAgZWXABFauC4arhxDOaULuRa8joDHUJbbYLpXOGdEbL0u2Mi3GpYcHXfVH8ukODCwTt5DBk",
	"ofSYfFxxQ7ghOcN0BRlhS8alQSd4xjWkqPTGPflDGgzPwBAuEyIVEmYII0uQoHlKCsdo/Fn+Nl6OCQvP",
	"5HYFQqhbcseF8IzC0uROaZGNcY23ZF6iIxjeZMB06/X485COPA8aRStgHENLG+wD9Zbn3F9dlvkctNUg",
	"R8iNxU4DllraX0qKChJtkLwbkMy97QiWwYKVAunsZDpNaM7WPC9zOjt1T1z6p5NaYC4RlqDp1oqswRRK",
	"GnBm/5vWypl9qiSCdFdhRSF4yuxVJn8ae5/7Fuu/a1jQGf3bpPGmiX9rJp7a1rG5kAhaMvFEHJIdxK8l",
	"rAtIrXOEPVaEb0zw7NI6unk0EQJV5yeOcvvW7xT+rkqZPRq3imDDZFsZgrvSuYYMJHIm3CMT4v2Czj7d",
	"00KrAjRyr+cv3MsE0lrGJ1owY+6UzuhNzKqb+PHJn2x2qfmfkCLdJvdUSQi89l3gMnBqC7q92d5sk8b4",
	"urJCtdzVcM7SFZcw0sAyNhdA3D6CbNn3zITmYAxbQp/MqsyZJDtEqt2HwPCiNdQjuLgA2r9UMIaPbvc9",
	"hTXLC+F8M2dLmBQyegueHRG0qzjRpmpjrI13sd0umHV225UJqknr1IHQl1DD/4qge8X/qrOipUa4JPMN",
	"gqFJw+/stBWlpv0oVa005hry3UKJDPRhm21QSjrAJ51kGe4wpMO33Ef2xqX2mbndfSEXynlGV/Uu8Hd+",
	"7CPkzKeGgDKt2aZ/QUepL/lNlcBtbuwbYaX5rs7ewR2xb9p6G3+WHxUxPC/EhmiweBGOCTGANnG5oqfU",
	"GiT6o3ccfXEkmEFiYJnbV+mKySVkIY/PyK6dkdHncjp9AfULz8llapenH2Ki2wG9XhdCsawPziL4bU12",
	"ziVzaXjQg/ZbYRDL0b3ZK8yHkJL7QvkA0BNAfWktz5USwGSPv/pCXQSJ8b6QBplM4QqwLD74urLPnWU5",
	"lzEzCskjJlppbNr38Wg/PvXOJJaOKll3DnmRjrjSEKLHQreXBTIsTZ+2GVjPGLI5M52QViiDS+0Co/kq",
	"OEIkrHnjuUKlQyprx0OzMQi5Pf4ierQo54Kn1x/edmP9CrEws8nEeKrj8GacqrztU6Xm0ahvwT1X9gRC",
	"dgSSjRRJA0P3Xj2qB40g4BxXUbc6G6gxWuVBxLs1y/th8qOt5m0cDGGSe06k7iNjeGlgodw7FCssz3r/",
	"/gpjoAI9Old16uKqWo5WYcenrTjuh/JYYBJPZBExh2vFyjOCVv4ofNF/80OVhnWRECkPSxnpI3e7Ry47",
	"qXd4CFH7+8mhUkvCGgfnHoG0m3iAAJvUE5v/50BKY5t8497fuvnGbeMKVtCCLblktiGzF3W9T6cKpD8t",
	"fppD9nI+enE6hdHZy5OfR+zllI3g9Cc4+/kkPWP/PLW1WimE1Uc1zOjpExUy0b+CWyZDCEbBOlSY7qjc",
	"K60SIEAZ03u3iTtsxFLhHwvXRv5Y9hvr5WYPaDWTxyolHM/kyIoioVdgDFeRygbWBddgXmGnEMwYwgh5",
	"DrEIb3keCo7XJmI97mDSYrlH0sEKLe1qYp8QnQZ815Jb72JiXIdLxorTg93p8WrkHSVGywADaak5bq7s",
	"rULV1WjTTc9Spb5waMZnas0zzb/BqNrYJKWC/wc2fpzEQ1xGji46vQ+nyKvLC5rQb6A9E3oyno6nrggv",
	"QLKC0xl94ZZ8X+BEmrCCu1bFPS3Baa4OgxcZnbnq37geM+mMogdyd7Nl4meONmMf2Ohn2kdsbM18tzc7",
	"E8LT6fTRhll1W70NE7wwxYyfqsWYdGeJbTNweNUG8OnGim/KPLeN28zlW8KEIOwb4y6J+OGztQC2NHUl",
	"TW25YQvyATWFltEbKxj8l8o2O6DkpUBeMI0T6w8jW+p+Hy6Bx7brEzblbZ9YIzs9qNfNmWeyXy91kffk",
	"mvQyEuaHSqhI5Z4RVW6Tlv9N7nm29anSNhdxBb/2777fEd0Xmyd3mVolZ4cBrgfQz6EVj1vQStypqkFU",
	"H3Q/o3oQ5kPO+DC4vWD/B0f8Htfrftv4Ia3j3E3/gnX8w5AckLm4OOyyPAxYBrPmzgTmCRWyw+nhGavG",
	"5Q1gGCB4DsRUl6lgqWHoIzNxsxJXi0XzVWcKRp/GSaLDw2f2l/i073/JXWfTl8+U6WoLcEJ3bYDJjKQa",
	"GEJY57YaJ27cSUKrsMc8WjVw1G9elbh6A3hVV8BPppiKRfWp8qhQ8SF8El+5uYImthi3XQVXtp8Vboqw",
	"89mhVcwHWFiJqz4kZthXLCjnDvM2Lo/vLztN3DN7SkshCV0By8I/Xq4AR+e+VerQagY0u43Tr+5rTRqe",
	"RjzzX29+IZcMV79OfiH/RizeSxH5ZhL88uS5Pc2rlzAi4a4yGedr7p8mlbelSntyGZdLUvePu4a1rZfu",
	"m79m+HZiPcq4KQTbvGuv29ar+l9O5bP9vfWr1nbHsr/VLVvXWY+QLd9oVRYdceqm1bUtoXXtVWX97VU0",
	"3TnRCjSRQ8Gwds4EsG62/w0AAP//pxmlE3AlAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
