//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.1-0.20240604070534-2f0ff757704b DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	TokenScopes = "token.Scopes"
)

// Defines values for CredentialsKind.
const (
	CredentialsKindPassword CredentialsKind = "password"
)

// Defines values for FileType.
const (
	FileTypeFile   FileType = "file"
	FileTypeFolder FileType = "folder"
)

// Defines values for InstanceStatusStatusDatabase.
const (
	Postgres InstanceStatusStatusDatabase = "postgres"
	Sqlite   InstanceStatusStatusDatabase = "sqlite"
)

// Defines values for InstanceStatusStatusFileStorage.
const (
	Filesystem InstanceStatusStatusFileStorage = "filesystem"
	S3         InstanceStatusStatusFileStorage = "s3"
)

// Defines values for PasswordCredentialsKind.
const (
	PasswordCredentialsKindPassword PasswordCredentialsKind = "password"
)

// Credentials defines model for Credentials.
type Credentials struct {
	Kind  CredentialsKind `json:"kind"`
	union json.RawMessage
}

// CredentialsKind defines model for Credentials.Kind.
type CredentialsKind string

// Error defines model for Error.
type Error struct {
	// Error machine-readable error tag
	Error string `json:"error"`

	// Message human readable error message
	Message string `json:"message"`
}

// File defines model for File.
type File struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Path string             `json:"path"`

	// Size Size of the file in bytes
	Size int      `json:"size"`
	Type FileType `json:"type"`
}

// FileType defines model for File.Type.
type FileType string

// FileList defines model for FileList.
type FileList struct {
	// Count number of items in the current slice of the collection
	Count int    `json:"count"`
	Items []File `json:"items"`

	// Next Cursor of the next element, to be used as the `after` parameter in paginated operations
	Next *string `json:"next"`

	// Total total number of items in the collection
	Total int `json:"total"`
}

// FileUpload defines model for FileUpload.
type FileUpload struct {
	File openapi_types.File `json:"file"`
	Path string             `json:"path"`
}

// FileUploadResponse defines model for FileUploadResponse.
type FileUploadResponse struct {
	Id string `json:"id"`
	Ok bool   `json:"ok"`
}

// InstanceSetupRequest defines model for InstanceSetupRequest.
type InstanceSetupRequest struct {
	Admin struct {
		Password string `json:"password"`
		Username string `json:"username"`
	} `json:"admin"`
}

// InstanceSetupResponse defines model for InstanceSetupResponse.
type InstanceSetupResponse struct {
	Ok bool `json:"ok"`
}

// InstanceStatus defines model for InstanceStatus.
type InstanceStatus struct {
	Status struct {
		Database       InstanceStatusStatusDatabase    `json:"database"`
		FileStorage    InstanceStatusStatusFileStorage `json:"fileStorage"`
		PublicURL      string                          `json:"publicURL"`
		SetupCompleted bool                            `json:"setupCompleted"`
	} `json:"status"`
}

// InstanceStatusStatusDatabase defines model for InstanceStatus.Status.Database.
type InstanceStatusStatusDatabase string

// InstanceStatusStatusFileStorage defines model for InstanceStatus.Status.FileStorage.
type InstanceStatusStatusFileStorage string

// ListInfo defines model for ListInfo.
type ListInfo struct {
	// Count number of items in the current slice of the collection
	Count int `json:"count"`

	// Next Cursor of the next element, to be used as the `after` parameter in paginated operations
	Next *string `json:"next"`

	// Total total number of items in the collection
	Total int `json:"total"`
}

// PasswordCredentials defines model for PasswordCredentials.
type PasswordCredentials struct {
	Kind     PasswordCredentialsKind `json:"kind"`
	Password string                  `json:"password"`
	Username string                  `json:"username"`
}

// PasswordCredentialsKind defines model for PasswordCredentials.Kind.
type PasswordCredentialsKind string

// Session defines model for Session.
type Session struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// SessionRequest defines model for SessionRequest.
type SessionRequest struct {
	Credentials Credentials `json:"credentials"`
}

// After defines model for After.
type After = string

// FilePrefix defines model for FilePrefix.
type FilePrefix = string

// First defines model for First.
type First = int

// InternalError defines model for InternalError.
type InternalError = Error

// FilesListParams defines parameters for FilesList.
type FilesListParams struct {
	// First Limit the number of items to return to only the first N
	First *First `form:"first,omitempty" json:"first,omitempty"`

	// After Cursor to fetch the next slice of the collection
	After *After `form:"after,omitempty" json:"after,omitempty"`

	// Prefix Prefix to filter files for. This is matched against the directory the files resides in, not as a generic prefix.
	// E.g. a prefix `hello` will match `hello/world.txt` but not `hello/dear/world.txt`.
	Prefix *FilePrefix `form:"prefix,omitempty" json:"prefix,omitempty"`
}

// FilesUploadMultipartRequestBody defines body for FilesUpload for multipart/form-data ContentType.
type FilesUploadMultipartRequestBody = FileUpload

// InstanceSetupJSONRequestBody defines body for InstanceSetup for application/json ContentType.
type InstanceSetupJSONRequestBody = InstanceSetupRequest

// AuthCreateSessionJSONRequestBody defines body for AuthCreateSession for application/json ContentType.
type AuthCreateSessionJSONRequestBody = SessionRequest

// AsPasswordCredentials returns the union data inside the Credentials as a PasswordCredentials
func (t Credentials) AsPasswordCredentials() (PasswordCredentials, error) {
	var body PasswordCredentials
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPasswordCredentials overwrites any union data inside the Credentials as the provided PasswordCredentials
func (t *Credentials) FromPasswordCredentials(v PasswordCredentials) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePasswordCredentials performs a merge with any union data inside the Credentials, using the provided PasswordCredentials
func (t *Credentials) MergePasswordCredentials(v PasswordCredentials) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Credentials) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["kind"], err = json.Marshal(t.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Credentials) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["kind"]; found {
		err = json.Unmarshal(raw, &t.Kind)
		if err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all available files
	// (GET /api/files)
	FilesList(w http.ResponseWriter, r *http.Request, params FilesListParams)
	// Upload a file to Oxidrive
	// (POST /api/files)
	FilesUpload(w http.ResponseWriter, r *http.Request)
	// Get the instance status
	// (GET /api/instance)
	InstanceStatus(w http.ResponseWriter, r *http.Request)
	// Setup the instance and create the initial admin user
	// (POST /api/instance/setup)
	InstanceSetup(w http.ResponseWriter, r *http.Request)
	// Create a new session and generate the corresponding token
	// (POST /api/sessions)
	AuthCreateSession(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// FilesList operation middleware
func (siw *ServerInterfaceWrapper) FilesList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params FilesListParams

	// ------------- Optional query parameter "first" -------------

	err = runtime.BindQueryParameter("form", true, false, "first", r.URL.Query(), &params.First)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "first", Err: err})
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		return
	}

	// ------------- Optional query parameter "prefix" -------------

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "prefix", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FilesList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// FilesUpload operation middleware
func (siw *ServerInterfaceWrapper) FilesUpload(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FilesUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// InstanceStatus operation middleware
func (siw *ServerInterfaceWrapper) InstanceStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InstanceStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// InstanceSetup operation middleware
func (siw *ServerInterfaceWrapper) InstanceSetup(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InstanceSetup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// AuthCreateSession operation middleware
func (siw *ServerInterfaceWrapper) AuthCreateSession(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthCreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/files", wrapper.FilesList)
	m.HandleFunc("POST "+options.BaseURL+"/api/files", wrapper.FilesUpload)
	m.HandleFunc("GET "+options.BaseURL+"/api/instance", wrapper.InstanceStatus)
	m.HandleFunc("POST "+options.BaseURL+"/api/instance/setup", wrapper.InstanceSetup)
	m.HandleFunc("POST "+options.BaseURL+"/api/sessions", wrapper.AuthCreateSession)

	return m
}

type ErrorJSONResponse Error

type InternalErrorJSONResponse Error

type FilesListRequestObject struct {
	Params FilesListParams
}

type FilesListResponseObject interface {
	VisitFilesListResponse(w http.ResponseWriter) error
}

type FilesList200JSONResponse FileList

func (response FilesList200JSONResponse) VisitFilesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FilesListdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FilesListdefaultJSONResponse) VisitFilesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type FilesUploadRequestObject struct {
	Body *multipart.Reader
}

type FilesUploadResponseObject interface {
	VisitFilesUploadResponse(w http.ResponseWriter) error
}

type FilesUpload200JSONResponse FileUploadResponse

func (response FilesUpload200JSONResponse) VisitFilesUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FilesUpload400JSONResponse struct{ ErrorJSONResponse }

func (response FilesUpload400JSONResponse) VisitFilesUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type FilesUploaddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response FilesUploaddefaultJSONResponse) VisitFilesUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type InstanceStatusRequestObject struct {
}

type InstanceStatusResponseObject interface {
	VisitInstanceStatusResponse(w http.ResponseWriter) error
}

type InstanceStatus200JSONResponse InstanceStatus

func (response InstanceStatus200JSONResponse) VisitInstanceStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InstanceStatusdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response InstanceStatusdefaultJSONResponse) VisitInstanceStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type InstanceSetupRequestObject struct {
	Body *InstanceSetupJSONRequestBody
}

type InstanceSetupResponseObject interface {
	VisitInstanceSetupResponse(w http.ResponseWriter) error
}

type InstanceSetup200JSONResponse InstanceSetupResponse

func (response InstanceSetup200JSONResponse) VisitInstanceSetupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type InstanceSetup400JSONResponse struct{ ErrorJSONResponse }

func (response InstanceSetup400JSONResponse) VisitInstanceSetupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InstanceSetup409JSONResponse Error

func (response InstanceSetup409JSONResponse) VisitInstanceSetupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type InstanceSetupdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response InstanceSetupdefaultJSONResponse) VisitInstanceSetupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type AuthCreateSessionRequestObject struct {
	Body *AuthCreateSessionJSONRequestBody
}

type AuthCreateSessionResponseObject interface {
	VisitAuthCreateSessionResponse(w http.ResponseWriter) error
}

type AuthCreateSession200JSONResponse Session

func (response AuthCreateSession200JSONResponse) VisitAuthCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthCreateSession401JSONResponse struct{ ErrorJSONResponse }

func (response AuthCreateSession401JSONResponse) VisitAuthCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AuthCreateSessiondefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response AuthCreateSessiondefaultJSONResponse) VisitAuthCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all available files
	// (GET /api/files)
	FilesList(ctx context.Context, request FilesListRequestObject) (FilesListResponseObject, error)
	// Upload a file to Oxidrive
	// (POST /api/files)
	FilesUpload(ctx context.Context, request FilesUploadRequestObject) (FilesUploadResponseObject, error)
	// Get the instance status
	// (GET /api/instance)
	InstanceStatus(ctx context.Context, request InstanceStatusRequestObject) (InstanceStatusResponseObject, error)
	// Setup the instance and create the initial admin user
	// (POST /api/instance/setup)
	InstanceSetup(ctx context.Context, request InstanceSetupRequestObject) (InstanceSetupResponseObject, error)
	// Create a new session and generate the corresponding token
	// (POST /api/sessions)
	AuthCreateSession(ctx context.Context, request AuthCreateSessionRequestObject) (AuthCreateSessionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// FilesList operation middleware
func (sh *strictHandler) FilesList(w http.ResponseWriter, r *http.Request, params FilesListParams) {
	var request FilesListRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FilesList(ctx, request.(FilesListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FilesList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FilesListResponseObject); ok {
		if err := validResponse.VisitFilesListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FilesUpload operation middleware
func (sh *strictHandler) FilesUpload(w http.ResponseWriter, r *http.Request) {
	var request FilesUploadRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FilesUpload(ctx, request.(FilesUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FilesUpload")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FilesUploadResponseObject); ok {
		if err := validResponse.VisitFilesUploadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InstanceStatus operation middleware
func (sh *strictHandler) InstanceStatus(w http.ResponseWriter, r *http.Request) {
	var request InstanceStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InstanceStatus(ctx, request.(InstanceStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InstanceStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InstanceStatusResponseObject); ok {
		if err := validResponse.VisitInstanceStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InstanceSetup operation middleware
func (sh *strictHandler) InstanceSetup(w http.ResponseWriter, r *http.Request) {
	var request InstanceSetupRequestObject

	var body InstanceSetupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InstanceSetup(ctx, request.(InstanceSetupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InstanceSetup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InstanceSetupResponseObject); ok {
		if err := validResponse.VisitInstanceSetupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthCreateSession operation middleware
func (sh *strictHandler) AuthCreateSession(w http.ResponseWriter, r *http.Request) {
	var request AuthCreateSessionRequestObject

	var body AuthCreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthCreateSession(ctx, request.(AuthCreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthCreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthCreateSessionResponseObject); ok {
		if err := validResponse.VisitAuthCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{
	"H4sIAAAAAAAC/7xY227bOBN+FYL/fykfkmZbxHfZoFsEKNqi2V61ATKWxjYbilTIUWM38LsveJAsWZKd",
	"3Ta5SkQOOTPfnD76kac6L7RCRZbPHnkBBnIkNP7rYkFo3D8Z2tSIgoRWfMYvS2O1YaTZAildMVohU7gm",
	"ZqVIkemFX0m1lJj6IwkX7tx9iWbDE64gRz7j4G9PuE1XmINTQ5vCbVgyQi35dpvwv4TETwYXYt01I6x7",
	"M4QkNO4PWrbQZsz+XgnLhGU5ULrCjMEShLLkDcuEwZS02fivcMigFRlaJlTClCYGlgFbokIjUlZ4ReNv",
	"6u14OWYQv9ntCqXUt+xBSBkUxaXJgzYyG9Oabtm8JH9h3MkQTGN7/G0InKCjhc5CmxzI7QGteNKLlrHU",
	"Beq9yEVwXZX5HI2LkCDMrcPOIJVGuf+0khUkxhL7MGCZ320ZluECSkl8djKdJjyHtcjLnM9O/ZdQ4euk",
	"NlgowiUavnUmG7SFVhZ9vr01Rvt8S7UiVN4VKAopUnCuTL5b589jQ/X/DS74jP9vskvjSdi1k3Db1qu5",
	"UoRGgXwmDcke4l8UrgtMCTNWyVSAeUcvDWaoSID0nyDlxwWffX3khdEFGhIBjzuhMvcXlUPwKy/A2gdt",
	"Mn7TF32D96UwmDlJf3InpeffMSW+TR65Vhh1HfLsU9TUNHR7s73ZJrsgtW3FarmNRA7pSigcGYQM5hKZ",
	"l2MEy24GJzxHa2GJ3WtWZQ6K7V1SSR8DI5i2u70HF99ouk6JrFV4ZSmyPrNDZTxyXENeyFAkEl2F90n7",
	"8m1Ju5UJ6Unj1JFiT7gVP3twuhY/6wbsbmNCsfmG0PJkp+/stFGX025dViu7xHNXeaNkhuZ49u1QSir7",
	"PUTR6iH834vQvXblcChFnfSVWmif1Xthc82t9c+hi3zoa6c5GAObrkv+pq7lN9H2L4XUkHUzaBHzqo7n",
	"XCjw7XQwLw5jG/H09w4BGYz5HFvrUFp3DNB3jeW51hJBdfTrOzcXepsLv1KWQKV4jVQWn/G+xBDQtnbI",
	"cqG6y3Vz6zOttK59hyo7jE8tmfS1y8rWvUPBpCe4NIToU6E7qIKAStu92w6sZ0AwB9sq1EJbWhq099IV",
	"270UhD3lGtLnmrSJzbZZ53ZjCXN3/FXv0aKcS5F++fy+3cNWRIWdTSY23DqOO+NU5812VhrR280cvJfa",
	"nSDMnoDlzopkB0Tbr86tR9MgIt0XpLrbdMKQ6lL1kK59qiVUYMWlMagOUeUa0pNjXdpx7kF2Hq/2vBwl",
	"5qgocSxvjqy0jhFbv3/rWfgtq4m/M7SApVDg2Itz1DOj1gDhrxev55idz0evTqc4Ojs/eTOC8ymM8PQ1",
	"nr05Sc/gj1PX9Esp3bzmMzIl9oSdNIHsuuCX2RCCvWAdm2l7kQ5BqwyIUPbFvY8IzX6BpyW/q895nckT",
	"213Cr9FaoXvaLq4LYdBeUGtKZUA4IpEj743aHarjFgaxpKHhgGGD0yJtA39okLfI6n7AG3u9fcBiWhpB",
	"m2t3WVBd++kV+G6EYPybNZ53TS/wfxF7AwnyFfJxLTIjfiC7+HTFE/4DTYCfn4yn46mftgUqKASf8Vd+",
	"KRAAr3gChfBk0H8t0cNSl+JVxmd+zFtPmJLWo32ANO1EJuGR6EjTEcHw+n+CYOORvr3Ze9KdTqe/7blV",
	"c8RtfHLFZ2f/qdqMSfvx1wy2xyuG+euNM96Wee742cx3fAZSMvgBwrex8FuBiz4sbT0uuaOAbu4OBCky",
	"w5COaOlPnW32IMlLSaIAQxNXgCM3z/4dKlHHtp31rulunzkee1QzROYsKDkclRiNZ49jsJBBeA+RZlVp",
	"9gRym4TaE5GSDZbfHmd7RpD3NP166tfAvMPwo1DlLLOVMxUsNQxdZCaeW/l23Zv6Ld58MPl/AzTN58YL",
	"10D/++C/lMHZ9PyFiqbOAG90OwdAZSw1CIRxXbiZyfwDyRFHczg9bJjmdjgxLkpaXXoFFSV5nuTY4xUv",
	"nBaVb1UinLx0aAPEDJjCBxaj4oPrf9SuwptqE67LhFqyirBV8YWSVi6223rpcfcjcJiE61EmbCFh86G5",
	"7jhDFKxzpCtbbzXEvcquqF92bX09Ili+M7osWubUbMtP3Mi5OlO6K15V796JRmL3HIqx3TsTwbrZ/hMA",
	"AP//h72VVVMZAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
