default:
    @just --list --unsorted | grep -v '  default'

test: setup
    bru run -r --env local --reporter-junit results.xml

setup:
    cargo run -p oxidrive -- create-account test --password test --if-not-exists
