version: '3'

services:
  oxidrive:
    image: ghcr.io/oxidrive/oxidrive:unstable
    build: ..
    environment:
      HOST: 0.0.0.0
      PORT: '5000'
      DATABASE_URL: postgres://oxidrive:oxidrive@postgres:5432/oxidrive?sslmode=disable
      PUBLIC_URL: http://localhost:5000
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: oxidrive
      POSTGRES_PASSWORD: oxidrive
      POSTGRES_DB: oxidrive
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oxidrive"]
      interval: 5s
      timeout: 5s
      retries: 5
