version: '3'

services:
  oxidrive:
    image: ghcr.io/oxidrive/oxidrive:unstable
    build: ..
    env_file: [.env.e2e]
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: oxidrive
      POSTGRES_PASSWORD: oxidrive
      POSTGRES_DB: oxidrive
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oxidrive"]
      interval: 5s
      timeout: 5s
      retries: 5
