openapi: "3.0.0"
info:
  title: Oxidrive API
  version: 1.0.0

components:
  securitySchemes:
    token:
      type: http
      scheme: bearer

  responses:
    Error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: machine-readable error tag
        message:
          type: string
          description: human readable error message
