openapi: "3.0.0"
info:
  title: Oxidrive API
  version: 1.0.0

components:
  schemas:
    GenericError:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: machine-readable error tag
        message:
          type: string
          description: human readable error message
