openapi: "3.0.0"
info:
  title: Oxidrive API
  version: 1.0.0

components:
  securitySchemes:
    session:
      type: apiKey
      in: cookie
      name: oxidrive-session

  responses:
    Error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
    InternalError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  parameters:
    After:
      name: after
      in: query
      required: false
      description: Cursor to fetch the next slice of the collection
      schema:
        type: string

    First:
      name: first
      in: query
      required: false
      description: Limit the number of items to return to only the first N
      schema:
        type: integer
        minimum: 1
        maximum: 200
        default: 100

  schemas:
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: machine-readable error tag
        message:
          type: string
          description: human readable error message

    NotFoundError:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          enum: [not_found]
        message:
          type: string
          description: human readable error message

    InvalidParamsError:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          enum: [invalid_params]
        message:
          type: string
          description: human readable error message

    ListInfo:
      type: object
      required:
        - count
        - total
        - next
      properties:
        count:
          type: integer
          description: number of items in the current slice of the collection
          minimum: 0
          example: 1
        total:
          type: integer
          description: total number of items in the collection
          minimum: 0
          example: 42
        next:
          type: string
          description: Cursor of the next element, to be used as the `after` parameter in paginated operations
          example: 6f6bed9b-320e-4917-a90a-e26e471c4a52
          nullable: true
