[package]
name = "oxidrive-ui"
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
tracing = { workspace = true }
vite-rs = { workspace = true }