[store]
dir = "target/nextest"

[test-groups.pg]
max-threads = 1

[test-groups.sqlite]
max-threads = "num-cpus"

[test-groups.s3]
max-threads = "num-cpus"

[profile.default]
default-filter = "not (test(::pg::) | test(::s3::))"
status-level = "all"
final-status-level = "fail"

failure-output = "final"
success-output = "never"

fail-fast = false

slow-timeout = { period = "20s" }
leak-timeout = "100ms"

[[profile.default.overrides]]
filter = 'test(::pg::)'
test-group = 'pg'

[[profile.default.overrides]]
filter = 'test(::sqlite::)'
test-group = 'sqlite'

[[profile.default.overrides]]
filter = 'test(::s3::)'
test-group = 's3'

[profile.full]
default-filter = "all()"

[profile.ci]
default-filter = "all()"

[[profile.ci.overrides]]
filter = 'test(::pg::)'
test-group = 'pg'
retries = { backoff = "exponential", count = 3, delay = "1s", jitter = true, max-delay = "10s" }

[[profile.ci.overrides]]
filter = 'test(::sqlite::)'
test-group = 'sqlite'
retries = { backoff = "exponential", count = 3, delay = "1s", jitter = true, max-delay = "10s" }

[[profile.ci.overrides]]
filter = 'test(::s3::)'
test-group = 's3'
retries = { backoff = "exponential", count = 3, delay = "1s", jitter = true, max-delay = "10s" }

[profile.ci.junit]
path = "junit.xml"
