default:
    @just --list --unsorted | grep -v '  default'


test:
    cargo nextest run --profile=ci

test-mutations:
    cargo mutants -vV --in-place --all-features

fmt:
    cd .. && cargo fmt --check

clippy:
    cargo clippy --all-targets --all-features

build-docker-image tag:
    nix build .#docker-image
    ./result -t {{ tag }} | docker load
