default:
    @just --list --unsorted | grep -v '  default'

test:
    cargo nextest run --profile=ci

test-mutations:
    cargo mutants -vV --in-place --all-features

fmt:
    cd .. && cargo fmt --check

clippy:
    cargo clippy --all-targets --all-features

build-and-push-image image tag:
    #!/usr/bin/sh
    nix build .#oci-image
    ./result > archive.tar.gz

    commit="$(git rev-parse --short HEAD)"
    src="docker-archive:./archive.tar.gz"

    skopeo copy "$src" "docker://{{ image }}:$commit"
    skopeo copy "$src" "docker://{{ image }}:{{ tag }}"
