[package]
name = "oxidrive-web"
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
app = { workspace = true }

axum = { workspace = true, features = ["macros"] }
serde = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["net"] }