[package]
name = "oxidrive-web"
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
app = { workspace = true }
oxidrive-auth = { workspace = true }

axum = { workspace = true, features = ["macros"] }
axum-extra = { workspace = true, features = ["typed-header", "cookie", "cookie-signed"] }
mime_guess = { workspace = true }
rust-embed = { workspace = true, features = ["axum"] }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["net"] }