build: setup
    npx astro check && npx astro build

watch: setup
    npx astro dev

astro *args:
    npx astro {{ args }}

setup:
    [ -d ../node_modules ] || npm install

fmt:
    npx biome format --write .

lint:
    npx biome ci .

