default:
    @just --list --unsorted | grep -v '  default'

build: setup
    npm run build

watch: setup
    npm run dev

astro *args: setup
    npm run astro {{ args }}

fmt: setup
    npm run format

lint *args: setup
    npm run lint -- {{ args }}

setup:
    [ -d ./node_modules ] || npm ci
