default:
    @just --list --unsorted | grep -v '  default'

build: setup
    npx astro check && npx astro build

watch: setup
    npx astro dev

astro *args: setup
    npx astro {{ args }}

setup:
    [ -d ./node_modules ] || npm ci

fmt: setup
    npx biome format --write .

lint: setup
    npx biome ci .

