name: Server

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-push:
    name: Build Docker image and push to registry
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build image
        run: nix develop --command just ci/build-docker-image ghcr.io/${{ github.repository }}:${{ inputs.tag }}

      - name: Push image
        id: build
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository }}:${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Sign image
        if: github.ref == 'refs/heads/main'
        run: |
          nix develop --command cosign sign --yes --key env://COSIGN_PRIVATE_KEY ghcr.io/${{ github.repository }}@${{ steps.build.outputs.digest }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
