name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review]
      branches:
        - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}
  TAG: unstable

jobs:
  e2e-tests:
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['chromium', 'firefox', 'webkit', 'Mobile Chrome', 'Mobile Safari']
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v7
    - uses: docker/setup-buildx-action@v3
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        working-directory: .
    - name: Run Playwright tests
      run: nix develop --command just e2e/test --project "${{ matrix.project }}"
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.project }}
        path: e2e/playwright-report/
        retention-days: 30
