name: OpenAPI Schema

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - .github/workflows/**
      - app/web/src/**
      - tools/generate-openapi/**
      - app/ui/src/lib/openapi.ts
  merge_group:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: openapi-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write

jobs:
  check-schema:
    if: github.event.pull_request.draft == false
    name: Check generated schema is up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix flake check

      - name: Generate schema
        run: nix develop --command just openapi-generate-schema
      - name: Check schema didn't change
        run: git diff --exit-code openapi.json

  check-generated-code:
    if: github.event.pull_request.draft == false
    name: Check generated TypeScript client is up to date
    runs-on: ubuntu-latest
    needs: [check-schema]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix flake check

      - name: Check formatting
        run: nix develop --command just openapi-generate-types --check
