name: OpenAPI Schema / Changes

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - openapi.json

concurrency:
  group: openapi-changes-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write

jobs:
  validate-schema-changes:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
    name: Validate OpenAPI schema for breaking changes
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Validate schema
        run: nix develop --command openapi-changes summary --global-revisions ./ ./openapi.json

      - name: Generate report
        if: '!cancelled()'
        run: nix develop --command openapi-changes html-report --global-revisions ./ ./openapi.json
      - uses: actions/upload-artifact@v4
        if: '!cancelled()'
        with:
          name: openapi-changes-report
          path: report.html
