name: Server CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - server/**
      - go.*
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - .github/workflows/**
      - server/**
      - go.*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: actions-go/go-install@0607b3e7a61b8f1b55e1169a884804d084db73af
        with:
          module: gotest.tools/gotestsum@latest
      - run: npx @redocly/cli@latest join -o server/openapi/out.yml server/openapi/openapi.yaml server/openapi/*.yaml
      - run: go mod download
      - run: go generate ./...
      - name: Run tests
        run: gotestsum --format testdox
        env:
          INTEGRATION_TEST: 'yes'
      - name: Run mutations
        uses: go-gremlins/gremlins-action@v1
        with:
          version: v0.5.0

  fmt:
    if: github.event.pull_request.draft == false
    name: Gofmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go mod download
      - name: Check formatting
        run: test -z $(gofmt -l .)

  vet:
    if: github.event.pull_request.draft == false
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npx @redocly/cli@latest join -o server/openapi/out.yml server/openapi/openapi.yaml server/openapi/*.yaml
      - run: go mod download
      - run: go generate ./...
      - name: Check for issues
        run: go vet ./...

  golangci:
    if: github.event.pull_request.draft == false
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npx @redocly/cli@latest join -o server/openapi/out.yml server/openapi/openapi.yaml server/openapi/*.yaml
      - run: go mod download
      - run: go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
