name: Unstable Build

on:
  push:
    branches:
      - main

concurrency:
  group: build-unstable-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write

jobs:
  build-and-push:
    uses: ./.github/workflows/build-image.yml
    with:
      tag: unstable
    secrets: inherit
