build: setup
    npx tailwindcss -i ./input.css -o ./assets/styles.css
    dx build --release

watch: setup
    npx concurrently "tailwindcss -i ./input.css -o ./assets/styles.css --watch" "dx serve --hot-reload"

setup:
    [ -d node_modules ] || npm install

fmt:
    cargo fmt
    dx fmt
    cargo clippy --allow-dirty --allow-staged --workspace --fix -- -D warnings

