build: setup
    npx tailwindcss -i ./input.css -o ./assets/styles.css
    dx build --release

watch: setup
    npx concurrently "just watch-app" "just watch-styles"

watch-app: setup
    dx serve --hot-reload

watch-styles: setup
    npx tailwindcss -i ./input.css -o ./assets/styles.css --watch

setup:
    [ -d node_modules ] || npm install

fmt:
    cargo fmt
    dx fmt
    cargo clippy --allow-dirty --allow-staged --workspace --fix -- -D warnings

