build: setup fmt
    #!/usr/bin/env sh
    cd app
    npx tailwindcss -i ./input.css -o ./assets/styles.css
    dx build --release

clean:
    rm -rf app/dist

watch: setup
    #!/usr/bin/env sh
    cd app
    npx concurrently "just watch-app" "just watch-styles"

watch-app: setup
    # https://github.com/DioxusLabs/dioxus/issues/2411
    # dx serve --hot-reload --bin oxidrive
    cargo watch -s 'dx build --bin oxidrive'

watch-styles: setup
    #!/usr/bin/env sh
    cd app
    npx tailwindcss -i ./input.css -o ./assets/styles.css --watch

test:
    cargo nextest run

setup:
    #!/usr/bin/env sh
    cd app
    [ -d node_modules ] || npm install

lint:
    cargo clippy --workspace -- -D warnings

fmt:
    dx fmt
    cargo fmt --all
    cargo clippy --allow-dirty --allow-staged --workspace --fix -- -D warnings

